-- MySQL Script generated by MySQL Workbench
-- Tue May 21 16:52:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consultatnt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consultatnt` (
  `idConsultatnt` INT NOT NULL,
  `date` DATE NULL,
  `dialog` MEDIUMTEXT NULL,
  `summary` MEDIUMTEXT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idConsultatnt`),
  INDEX `fk_Consultatnt_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Consultatnt_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Survey` (
  `idSurvey` INT NOT NULL,
  `score` VARCHAR(45) NULL,
  `Consultatnt_idConsultatnt` INT NOT NULL,
  PRIMARY KEY (`idSurvey`),
  INDEX `fk_Survey_Consultatnt1_idx` (`Consultatnt_idConsultatnt` ASC) VISIBLE,
  CONSTRAINT `fk_Survey_Consultatnt1`
    FOREIGN KEY (`Consultatnt_idConsultatnt`)
    REFERENCES `mydb`.`Consultatnt` (`idConsultatnt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
