"""add chatbot table

Revision ID: 33951703d4c1
Revises: ab624bada959
Create Date: 2024-08-05 07:22:13.798280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33951703d4c1'
down_revision = 'ab624bada959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialog_url', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('feedback', mysql.ENUM('good', 'bad'), nullable=True),
    sa.Column('faceimage_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['faceimage_id'], ['faceimage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.idUser'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    op.drop_table('chatbot')
    # ### end Alembic commands ###
