"""not allowing null at faceimage_id

Revision ID: 3e25b600b9c0
Revises: 486f0da0b360
Create Date: 2024-08-11 09:57:56.134595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e25b600b9c0'
down_revision = '486f0da0b360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.alter_column('faceimage_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.alter_column('faceimage_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
