"""image_url include and delete image_data

Revision ID: 4ec2b75860a2
Revises: 55b2c37c3881
Create Date: 2024-08-25 08:45:20.762530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ec2b75860a2'
down_revision = '55b2c37c3881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.MEDIUMBLOB(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
