"""Initial migration

Revision ID: 55b2c37c3881
Revises: 
Create Date: 2024-08-24 05:20:03.995945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55b2c37c3881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('nickname', sa.String(length=45), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('faceimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', mysql.MEDIUMBLOB(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.idUser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialog', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('summary', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('feedback', mysql.ENUM('good', 'bad'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('faceimage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faceimage_id'], ['faceimage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.idUser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot')
    op.drop_table('faceimage')
    op.drop_table('user')
    # ### end Alembic commands ###
