"""Add dialog to Chatbot table

Revision ID: 5ca1f557d989
Revises: 1deeb092410d
Create Date: 2024-08-11 08:47:58.747256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ca1f557d989'
down_revision = '1deeb092410d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialog', mysql.MEDIUMTEXT(), nullable=False))
        batch_op.drop_constraint('chatbot_ibfk_1', type_='foreignkey')
        batch_op.drop_column('faceimage_id')
        batch_op.drop_column('dialog_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialog_url', mysql.MEDIUMTEXT(), nullable=False))
        batch_op.add_column(sa.Column('faceimage_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('chatbot_ibfk_1', 'faceimage', ['faceimage_id'], ['id'])
        batch_op.drop_column('dialog')

    # ### end Alembic commands ###
