"""second migration

Revision ID: 63b6d33722ed
Revises: 
Create Date: 2024-07-28 07:59:01.411883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63b6d33722ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 이미 존재하지 않는 테이블 삭제 명령 주석 처리
    # op.drop_table('survey')
    # op.drop_table('consultant')
    
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=mysql.BLOB(),
               existing_nullable=True)

    op.create_table('consultant',
    sa.Column('idConsultant', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('dialog', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('summary', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.idUser'], name='consultant_ibfk_1'),
    sa.PrimaryKeyConstraint('idConsultant'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('survey',
    sa.Column('idSurvey', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consultantId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', mysql.ENUM('醫뗭쓬', '?レ쓬'), nullable=False),
    sa.ForeignKeyConstraint(['consultantId'], ['consultant.idConsultant'], name='survey_ibfk_2'),
    sa.ForeignKeyConstraint(['userId'], ['user.idUser'], name='survey_ibfk_1'),
    sa.PrimaryKeyConstraint('idSurvey'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
