"""Fix cascade delete

Revision ID: faa702c35b7a
Revises: 3e25b600b9c0
Create Date: 2024-08-14 03:54:29.771744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa702c35b7a'
down_revision = '3e25b600b9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.drop_constraint('chatbot_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('chatbot_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'faceimage', ['faceimage_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['idUser'], ondelete='CASCADE')

    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['idUser'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faceimage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user', 'user', ['user_id'], ['idUser'])

    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chatbot_ibfk_3', 'faceimage', ['faceimage_id'], ['id'])
        batch_op.create_foreign_key('chatbot_ibfk_2', 'user', ['user_id'], ['idUser'])

    # ### end Alembic commands ###
